default: &default
  adapter: mysql2
  encoding: utf8
  host: localhost
  username: root
  password: huawei

development:
  <<: *default
  database: fast_ci_development

test:
  <<: *default
  database: fast_ci_test

production:
  <<: *default
  database: fast_ci
