default: &default
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  username: fast_ci
  password: huawei

development:
  <<: *default
  database: fast_ci_development

test:
  <<: *default
  database: fast_ci_test

production:
  <<: *default
  database: fast_ci
